name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: "Playwright Tests - ${{ matrix.project }}"
    strategy:
      fail-fast: false
      matrix:
        # project: [chromium, firefox, webkit]
        # only firefox is working reliably
        project: [firefox]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./testing
    steps:
      - uses: actions/cache@v2
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/checkout@v4
        with:
          lfs: "true"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - run: npx playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit == 'true'
      - run: npx elm make TestApp.elm --output=TestApp.html
      - uses: coactions/setup-xvfb@v1
        with:
          run: npx playwright test --project=${{ matrix.project }}
          working-directory: ./testing
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.project }}
          path: testing/playwright-report/
          retention-days: 30
